name:                populational-heuristics
version:             0.1.0.0
github:              "ViniciusATR/populational-heuristics"
license:             BSD3
author:              "Vinicius Resende"
maintainer:          "viniatresnde@gmail.com"
copyright:           "2021 Vinicius Resende"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/populational-heuristics#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - random
    - mtl
    - containers

executables:
  populational-heuristics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - populational-heuristics

tests:
  populational-heuristics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - populational-heuristics
    - tasty
    - tasty-hunit
    - random
    - mtl
    - containers
